
package com.avectra._2005;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * Avectra Xml Web Services with Authentication Token release:
 * http://www.avectra.com/2005/ - For additional information or for questions
 * concerning xWeb please navigate to netForum xWeb Online help at
 * http://wiki.avectra.com/index.php?title=XWeb. Please note: all xWeb message
 * exchanges are recommended to occur over SSL.
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "netForumXML", targetNamespace = "http://www.avectra.com/2005/", wsdlLocation = "http://access.personalcarecouncil.org/xweb/secure/pcpcxml.asmx?wsdl")
public class NetForumXML extends Service {

	private final static URL	NETFORUMXML_WSDL_LOCATION;
	private final static Logger	logger	= Logger.getLogger(com.avectra._2005.NetForumXML.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.avectra._2005.NetForumXML.class.getResource(".");
			//url = new URL(baseUrl, "http://access.personalcarecouncil.org/xweb/secure/pcpcxml.asmx?wsdl");
			 url = new URL(baseUrl, "http://access.personalcarecouncil.org/nFPCPCTest/xweb/secure/pcpcxml.asmx?wsdl");
		}
		catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://access.personalcarecouncil.org/xweb/secure/pcpcxml.asmx?wsdl', retrying as a local file");
			// logger.warning("Failed to create URL for the wsdl Location:
			// 'http://access.personalcarecouncil.org/nFPCPCTest/xweb/secure/pcpcxml.asmx?wsdl',
			// retrying as a local file");
			logger.warning(e.getMessage());
		}
		NETFORUMXML_WSDL_LOCATION = url;
	}

	public NetForumXML(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public NetForumXML() {
		super(NETFORUMXML_WSDL_LOCATION, new QName("http://www.avectra.com/2005/", "netForumXML"));
	}

	/**
	 * 
	 * @return returns NetForumXMLSoap
	 */
	@WebEndpoint(name = "netForumXMLSoap")
	public NetForumXMLSoap getNetForumXMLSoap() {
		return super.getPort(new QName("http://www.avectra.com/2005/", "netForumXMLSoap"), NetForumXMLSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns NetForumXMLSoap
	 */
	@WebEndpoint(name = "netForumXMLSoap")
	public NetForumXMLSoap getNetForumXMLSoap(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.avectra.com/2005/", "netForumXMLSoap"), NetForumXMLSoap.class, features);
	}

	/**
	 * 
	 * @return returns NetForumXMLHttpGet
	 */
	@WebEndpoint(name = "netForumXMLHttpGet")
	public NetForumXMLHttpGet getNetForumXMLHttpGet() {
		return super.getPort(new QName("http://www.avectra.com/2005/", "netForumXMLHttpGet"), NetForumXMLHttpGet.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns NetForumXMLHttpGet
	 */
	@WebEndpoint(name = "netForumXMLHttpGet")
	public NetForumXMLHttpGet getNetForumXMLHttpGet(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.avectra.com/2005/", "netForumXMLHttpGet"), NetForumXMLHttpGet.class, features);
	}

	/**
	 * 
	 * @return returns NetForumXMLHttpPost
	 */
	@WebEndpoint(name = "netForumXMLHttpPost")
	public NetForumXMLHttpPost getNetForumXMLHttpPost() {
		return super.getPort(new QName("http://www.avectra.com/2005/", "netForumXMLHttpPost"), NetForumXMLHttpPost.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns NetForumXMLHttpPost
	 */
	@WebEndpoint(name = "netForumXMLHttpPost")
	public NetForumXMLHttpPost getNetForumXMLHttpPost(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.avectra.com/2005/", "netForumXMLHttpPost"), NetForumXMLHttpPost.class, features);
	}

}
